config/routes.rb
Rails.application.routes.draw do
  
  resources :details
  
  post "/" => 'paypal#handle'
  post '/paypal' => 'paypal#validate'
  
  get 'static_page/admin'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

 get 'admins/sign_up' => 'page#home' #this stops unauthorised admin sign up
  devise_for :admins
  
 

  
  get '/cart' => 'cart#index'
  get '/cart/order/:id' => 'cart#order'
  
  get '/cart/clear' => 'cart#clearCart'
 
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'

  resources :products
  resources :products
  
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  
 post '/search' => 'products#search'

resources :contactus
get 'page/contactus'
  
  get 'contactus/index'

  devise_for :users
  
  root 'page#home'
  
  resources :users
  
  resources :orders
  get 'orders/confirm/:id' => 'orders#confirm'
  
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :order_status
<<<<<<< HEAD
end
=======
  has_many :order_items
   before_create :set_order_title
  before_create :set_order_status
  before_save :update_subtotal
  
  
  
  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
  
  def confirm
    self.order_status_id = 2
    
  end
  
  def finish
   self.order_status_id = 3
  end
  
private
  def set_order_status
    self.order_status_id = 1
  end
  
   def set_order_title
    self.title = "Pending"
  end


  def update_subtotal
    self[:subtotal] = subtotal
  end
end


>>>>>>> orders

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
<<<<<<< HEAD
<<<<<<< HEAD
end
=======
=======
  belongs_to :user
>>>>>>> orders

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present
  

  before_save :finalize
  

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end
>>>>>>> orders

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
  has_many :order_items
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  @orders = Order.all
  
  before_action :authenticate_user!, except: [:index]
  @products = Product.all
  
 def add
    id = params[:id]
    
    cart = session[:cart] ||= {}
    cart[id] = (cart[id] || 0) + 1
        
    redirect_to :action => :index
  end
  
  
 # def decrease
  #  id = params[:id]
   # cart = session[:cart] ||= {}
    #cart[id] = (cart[id] || 0) - 1
    #redirect_to :action => :index
  #end
 
 
  #def index
      #create_cart
  #  @order_items = current_order.order_items
  #end


 def clearCart
    session[:order_id] = nil
    redirect_to :action => :index
     flash[:notice] = 'Order Finished'
   end





  def index
    @order_items = current_order.order_items
    @orders = Order.all
    
  end
  
  
  def order
    order_id = params[:id]
    @order = Order.find_by_id(order_id)
    @user = User.find_by_id(@order.user_id)
    puts @user
   @order = Order.find_by_id(order_status_id)
  end
  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


end

app/controllers/page_controller.rb
class PageController < ApplicationController
def home
    
    @products = Product.all
    
     @orders = Order.all
   
   @details = Detail.all
end 
   
end

app/controllers/paypal_controller.rb
class PaypalController < ApplicationController
  
  
  def confirm
    self.order_status_id = 2
    redirect_to :action => :index
   
  end
  
  def validate
   if params[:item_number] == "3"
      
  end
    
    item_name = params[:item_name]
    arr = item_name.split(" ")
    id = arr[-1].to_i
    
     
    @order = Order.find_by_id(id)
    @order.finish
    @order.save
    
    
    # some code to destroy the cart / reset so we can't submit cart
    
    redirect_to '/cart'
  end
  
  def handle
    redirect_to "/cart/clear"
    flash[:notice] = 'Transaction Complete'
    @order = Order.last
    @order.update_attribute(:title , "Paid by User:#{current_user.id} #{current_user.name} #{current_user.surname}")
  end
  
  def updatetitle
    
  end
  
    def clearCart
    session[:order_id] = nil
   end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
 
end

app/helpers/paypal_helper.rb
module PaypalHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency(current_order.subtotal, :unit => '€')} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_login.html.erb
    <div class="popupl">
<div class="popuphead">
  <p>Welcome back please Log in</p>
</div>
   <p>         
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
 <div class="popipl">
   
  
  <div class="field">
    
    <%= f.email_field :email, autofocus: true, :class => "fieldbox",placeholder: 'Enter E-Mail address' %>
  </div>

  <div class="field">
    
    <%= f.password_field :password, :class => "fieldbox", autocomplete: "off",placeholder: 'Enter your passeword' %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in", :class => "formbutton" %>
  </div>
  
  <p>
    <button class="formbutton" onmousedown="toggleOverlay()">Cancel</button>
    
 <p><%= render "devise/shared/links" %></p>
 

  </div>
<% end %>
</div>

app/views/layouts/_rotate.html.erb
<div class="wraper">
		<div class="rotator"><img class="rotatimg" src="/assets/main-1.png"  alt="an image"/></div>
		</div>

app/views/layouts/_total.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency(current_order.subtotal, :unit => '€')} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
		<meta charset="UTF-8">


				<meta name="GENERATOR" content="Created by L. McCabe, D. Atanasova">

					<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  				<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    			<%= javascript_include_tag :defaults %>
    			<%= csrf_meta_tags %>
    			
    			
    			
    		
    
						<meta name="viewport" content="initial-scale=1, maximum-scale=1">
	
	

			<title>Charma Jewellery</title>





	<!-- script for overlay -->
	<script>
				function toggleOverlay(){
	
				var overlay = document.getElementById('overlay');
				var specialBox = document.getElementById('specialBox');
						overlay.style.opacity = .8;
		
				if(overlay.style.display == "block"){
						overlay.style.display = "none";
						specialBox.style.display = "none";
					} 
				
				else {
							overlay.style.display = "block";
							specialBox.style.display = "block";
							}
			}

	</script>
	
	




</head>

<body>

																						<!-- Start Overlay -->
																						<div id="overlay"></div>
																						<!-- End Overlay -->
																						<!-- Start Special Centered Box -->
																						<div id="specialBox">
																						<%= render 'layouts/login' %>
  					 		
				  																 </div>
																						<!-- End Special Centered Box -->
																				

	<div class="header">
	
		<div class="contacts">
		<img id="phone" class="contactimg" src="/assets/phone3.jpg"  alt="an image" onmousedown="cartcontent()"/>
		<img class="contactimg" src="/assets/phone2.jpg"  alt="an image"/>
		
		<a href="/cart"><img id="cartimage" class="contactimg" src="/assets/trolley.jpg"  alt="an image" onmouseover="cartcontent()"/></a>
		<div id="cartshow" >
	 <%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency(current_order.subtotal, :unit => '€')} )", cart_path, class: "btn btn-link" %>
	  </div>
	  
	  <script>

  $("#cartimage").on("mouseenter", function() {
      $("#cartshow").slideDown("slow");
      }).on("mouseleave", function() {
      $("#cartshow").slideUp("slow");
  });

	</script>
	  
	  
	  
	  
	  
	
		</div>
		
		<div class="logo">
		<a href="/"><img class="logoimg" src="/assets/LOGO_JPG.jpg"  alt="an image"/></a>
<<<<<<< HEAD
		<% if admin_signed_in? %>
=======
			<% if admin_signed_in? %>
>>>>>>> orders
			<p>Administrator Control Active</p>
			<% end %>
		</div>
		
		<!-- Start of social media links and log-in section -->
		
		<div class="social">
		
		<!-- start of log-in -->
		<div class="login">
			
			
			
			<% if user_signed_in? %>
 
 		 	Welcome <strong><%= current_user.name %> </strong>.
  			
  			<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
				<% else %>
  			<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  		<button onmousedown="toggleOverlay()"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></button>
		
		<% end %>
			
			<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
			<% end %>
			<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
			<% end %>
			
		</div>
		
		<!-- End of log in information -->
		
		<!-- start of social media links -->
		<img class="socialimg" src="/assets/fb.jpg"  alt="an image"/>
		<img class="socialimg" src="/assets/pinterest.jpg"  alt="an image"/>
		<img class="socialimg" src="/assets/youtube.jpg"  alt="an image"/>
		
		<div class="searchdiv">
   <h2>Search</h2>
   <%= render :partial => 'products/search' %>
</div>
		</div>
		
		<!-- end of social media links -->


	
	
	</div>

<!-- this is the image rotater html -->



	<%= render 'layouts/rotate' %>
	
		
		
		<div class="wraper">
		
						<nav class="navwraper">
						<ul class="navwraper">
						<a href="/"><li class="nav">Home</li></a>
						<% if user_signed_in? %>
							<a href="/cart"><li class="nav">Cart</li></a>
							<% else %>
							<a href="/cart" onmousedown="toggleOverlay()"><li class="nav">Cart</li></a>
						<% end %>
							<a href="/products" ><li class="nav" onclick="myFunction()">Products</li></a>
							<div id="myDropdown" class="dropdown-content">
								<button onclick="myFunction()" class="dropbtn">Product</button>
    <a href="#home">Home</a>
    <a href="#about">About</a>
    <a href="#contact">Contact</a>
  </div>
  <script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
						<li class="nav">About</li>
						<a href="/contactus"><li class="nav">Contact</li></a>
						</ul>
						</nav>
							


	
	

	
	
	<%= yield %>
	
				
		
						
		

			
</div>


<div class="footer">
		
			
			
			<div class="footerdiv"><h2>Charma Jewelery</h2><p>Address: Here, There and Everywhere</p><p>Phone: 080 0000000</p></div>
			
			
			<div class="footerdiv"><h2>Website Development By</h2><p>Liam McCabe</p><p>Denitsa Atanasova</p></p><p>NCI 2015</p></div>
			
			<div class="footerdiv"><p>
				<h2>Useful Information</h2>
				<p>Terms & Conditions</p>
				<p>Return Policy</p>
				<p>Vacancies</p>
				
			 
			
					</p>
			</div>
			
			
				<div class="footerdiv">
				<h2>Admin Section</h2>
				<p><% if admin_signed_in? %>
 
 		 	  Welcome <strong><%= current_admin.name %></strong>.
  			
  			<%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
				<% else %>
  			
  			<%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
		
					<% end %>	
					</P>
					<a href="/details"><p>Control Pannell</p></a>
				
				
				
				</div>


</div>
</body>

</html>

app/views/page/home.html.erb
<!-- start of colections promo -->
<div class="featurewraper">
		<div class="featureda"><h2>2016 COLLECTION</h2></div>
		<div class="featuredb"><h2>SPECIALS</h2></div>
</div>

<!-- start of colections promo -->
		
	
	
		<!-- start of company promo text -->
		<div class="featurewraper">
			<h2><%= render 'layouts/cart_text' %></h2>
			<h2>Welcome to Charma Jewellery Online now</h2>

			<p><%= @details.last.welcome %></p>
		</div>
		<!-- end of company promo text -->
		
		
		<!-- end of features and feedback -->
			
		
		<div class="featurewraper">
		<h2>Featured Products</h2>
				<div class="featuredc">
					<h2><%= @products.last.title %></h2>
					<img class="featureimg" src="/assets/<%= @products.last.image_name %>"  alt="an image"/>
					<p>
					<%= number_to_currency(@products.last.price, :unit => '€') %>
					</p>
				
					<a href="products/<%=@products.last.id%>"><button class="formbutton" type="button">Details!</button></a>
						
					
				</div>
		
		
		
				<div class="featuredc">
					<h2>Some Product</h2>
					<img class="featureimg" src="/assets/DSC_0108.JPG"  alt="an image"/>
					<p>€99
					</p>
					<button class="formbutton" type="button">Details!</button>
						
				</div>
		
				
		
				<div class="featuredc">
					<h2>Some Product</h2>
					<img class="featureimg" src="/assets/DSC_0108.JPG"  alt="an image"/>
					<p>€99
					</p>
					<button class="formbutton" type="button">Details!</button>
	
		</div>
		
		
		<div class="featurewraper">
		<h2>Customer reviews</h2>
				<div class="featuredc">
					<h2>Yvonne, Navan</h2>
					<p>Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the 
					embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document.
					</p>
					
				</div>
		
		
		
				<div class="featuredc">
					<h2>Chloe, Perth</h2>
					<p>Video provides a powerful way to help you prove your point. When you click Online Video, you can paste in the 
					embed code for the video you want to add. You can also type a keyword to search online for the video that best fits your document.
					</p>
					
				</div>
		<div class="featuredc">
			<h2>News Feed</h2>
			<p><%= @details.last.about %></p>
		
		
		</div>
		
		</div>
		
		
		




	</div>

		



			<!-- end of features and feedback -->
		
		