config/routes.rb
Rails.application.routes.draw do
  
  resources :details
  
  post "/" => 'paypal#handle'
  post '/paypal' => 'paypal#validate'
  
  get 'static_page/admin'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

 get 'admins/sign_up' => 'page#home' #this stops unauthorised admin sign up
  devise_for :admins
  
 

  
  get '/cart' => 'cart#index'
  get '/cart/order/:id' => 'cart#order'
  
  get '/cart/clear' => 'cart#clearCart'
 
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'

  resources :products
  resources :products
  
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  
 post '/search' => 'products#search'

resources :contactus
get 'page/contactus'
  
  get 'contactus/index'

  devise_for :users
  
  root 'page#home'
  
  resources :users
  
  resources :orders
  get 'orders/confirm/:id' => 'orders#confirm'
  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def search
     @search_term = params[:q]
     st = "%#{params[:q]}%"
     @products = Product.where("title like ? or long_des like ?", st, st)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  
  
  
  
  
  
  
  
    # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
    @user = current_user
     @details = Detail.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = Product.all
    @order_item = current_order.order_items.new
    @user = current_user
    @product = Product.find(params[:id])
    @details = Detail.all
  end

  # GET /products/new
  def new
    @product = Product.new
    @details = Detail.all
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
@details = Detail.all
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :short_des, :long_des, :price, :image_name, :discount, :category, :sub_category, :image_2, :inage_3)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comment.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
                  <%= f.label :"Customer Reviews" %><br>
                  <ol><li>Look Here</li></ol>
                    <input type="text" value="2" name="product[inage_3]" id="product_inage_3" />
                  </div>
                  <%= @product.inage_3 %>
                  <div class="actions">
                  <%= f.submit %>
                  </div>
                  <% end %>
  
             


<div id="flip"><p>See Customer Reviews...</p></div>
								<!-- start of dropdown panel -->
							<div id="panel">
							
							<!-- Start of apend script and div -->

									<script>
										$(document).ready(function(){
											$("#btn2").click(function(){
											$("li").append("<br><br> " + "Username: " +  $("#test").val());
											});
										});

										$(document).ready(function(){
											$("button").click(function(){
											$("#test").text($("#test").val()) ;
											});
										});

										$(document).ready(function(){
											$("#flip").click(function(){
											$("#panel").slideToggle("slow");
											});
										});
									</script>

									<!-- End of apend div and script -->

								
									<ol>
									<li>Customer Reviews of this item:</li>
								
									<!-- User input to change text -->
									<p><input class="niceinput" type="text" id="test" value="Js one"></p>
									<!-- User input to change text -->
									<button class="formbutton" id="btn2">Leave Review</button>







		
		
		
		
							</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :short_des %><br>
    <%= f.text_field :short_des %>
  </div>
  <div class="field">
    <%= f.label :long_des %><br>
    <%= f.text_area :long_des %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_name %><br>
    <%= f.text_field :image_name %>
  </div>
  <div class="field">
    <%= f.label :discount %><br>
    <%= f.number_field :discount %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :sub_category %><br>
    <%= f.text_field :sub_category %>
  </div>
  <div class="field">
    <%= f.label :image_2 %><br>
    <%= f.text_field :image_2 %>
  </div>
  <div class="field">
    <%= f.label :inage_3 %><br>
    <%= f.text_field :inage_3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
	<!-- Start of products each wrapper -->
		
				
					<div class="featuredc">
					<h2><%= product.title %></h2>
					<img class="prodimg" src="/assets/<%= product.image_name %>"  alt="an image"/>
					<p>
					<%= product.short_des %>
					</p>
					<p><button class="formbutton"><%= link_to 'Details...', product %></button></p>
					<%= form_for order_item, remote: true do |f| %>
      
          <p>Unit Price: <span style="color: green"><%= number_to_currency(product.price, :unit => '€') %></span></p>
                           
                            
                            
          <% if admin_signed_in? %>
          <p><%= link_to 'Edit', edit_product_path(product) %> </p>
          <p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>     
          
          
          <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
          <%= f.hidden_field :product_id, value: product.id %>
             
         <% if user_signed_in? %>
         <%= f.submit "Add to the Cart", class: "formbutton" %>
         <% else %>
         <p><a href="cart/<%= product.id %>"><button class="formbutton" onmousedown="toggleOverlay()">Add to Cart</button></a></p>
         <% end %>
         </div>
         </div>
         <% end %>
          
				
	        </div>
		

		
    
  <!-- end of products each wrapper -->

app/views/products/_reviewtext.html.erb
									<ol>
									<li>Reviews</li>
									</ol>

app/views/products/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="featurewraper">
	  	<h2>Featured Products</h2>


<% if admin_signed_in? %>
  <h2><%= link_to 'Add New Product', new_product_path %></h2>
 
<% end %>



<% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>

</div>





 

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<div class="featurewraper">

<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @products.length == 0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>


<% @products.each do |product| %>
  
              	<div class="featuredc">
					<h2><%= link_to product.title, product %></h2>
					<img class="featureimg" src="/assets/<%= product.image_name %>"  alt="an image"/>
					<p><%= product.short_des %></p>
					<p><%= product.price %>
					</p>
					<p><a href="products/<%=product.id%>"><button class="formbutton" type="button">Details!</button></a></p>
						
				</div>
  

<% end %>



</div>

app/views/products/show.html.erb
<div class="featurewraper">
		<h2><%= @product.title %></h2>
	
			<div class="one">
				
					<div class="featuredd">
					<h2>About This Product</h2>
						
					<img class="showimg" src="/assets/<%= @product.image_name %>"  alt="an image"/>
				
				<p><%= number_to_currency(@product.price, :unit => '€') %></p>
				
				
				<%= render 'comment' %>
			
			<!-- From Here -->
			
			<%= form_for @order_item, remote: true do |f| %>
      
          <p>Unit Price: <span style="color: green"><%= number_to_currency(@product.price, :unit => '€') %></span></p>
                           
                            
                            
          <% if admin_signed_in? %>
          <p><%= link_to 'Edit', edit_product_path(@product) %> </p>
          <p><%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>     
          
          
          <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
          <%= f.hidden_field :product_id, value: @product.id %>
             
         <% if user_signed_in? %>
         <%= f.submit "Add to the Cart", class: "formbutton" %>
         <% else %>
         <p><a href="cart/<%= @product.id %>"><button class="formbutton" onmousedown="toggleOverlay()">Add to Cart</button></a></p>
         <% end %>
         </div>
         </div>
         
         <% end %>
      
         <!-- to here -->
				
				
				
				
				
				
				
				
				
				
				
				
				
				
				
		
 
						
		
				</div>
		
			</div>
			
			<div class="two">
			<div class="featuredd">
					<h2><%= @product.title %></h2>
					<p id="notice"><%= notice %></p>
					
					
					
					
					
					
					
					
					
					
					
					
					<p>
					<%= @product.long_des %>
					</p>
					<p>
					<%= @product.long_des %>
					<p><% if admin_signed_in? %>
  				<%= link_to 'Edit', edit_product_path(@product) %>
  
  				<% end %>
  				<%= link_to 'Back', products_path %></p>
					</p>
					
				</div>
			
			
			</div>
			
		
		
		
		
				
		
				
		


	
				
		
						
		

			
		</div>