config/routes.rb
Rails.application.routes.draw do
  
  resources :details
  
  post "/" => 'paypal#handle'
  post '/paypal' => 'paypal#validate'
  
  get 'static_page/admin'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

 get 'admins/sign_up' => 'page#home' #this stops unauthorised admin sign up
  devise_for :admins
  
 

  
  get '/cart' => 'cart#index'
  get '/cart/order/:id' => 'cart#order'
  
  get '/cart/clear' => 'cart#clearCart'
 
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/decrease/:id' => 'cart#decrease'

  resources :products
  resources :products
  
  
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  
 post '/search' => 'products#search'

resources :contactus
get 'page/contactus'
  
  get 'contactus/index'

  devise_for :users
  
  root 'page#home'
  
  resources :users
  
  resources :orders
  get 'orders/confirm/:id' => 'orders#confirm'
  
  

end

app/models/detail.rb
class Detail < ActiveRecord::Base
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  # GET /details
  # GET /details.json
  def index
    @details = Detail.all
   @products = Product.all
   @orders = Order.all
   @users= User.all
    @order_items = current_order.order_items
@orderItem = OrderItem.all
  end

  # GET /details/1
  # GET /details/1.json
  def show
    @details = Detail.all
  end

  # GET /details/new
  def new
    @detail = Detail.new
    @details = Detail.all
  end

  # GET /details/1/edit
  def edit
    @details = Detail.all
  end

  # POST /details
  # POST /details.json
  def create
    
    
    @detail = Detail.new(detail_params)
@details = Detail.all
    respond_to do |format|
      if @detail.save
        format.html { redirect_to @detail, notice: 'Detail was successfully created.' }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1
  # PATCH/PUT /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to @detail, notice: 'Detail were successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1
  # DELETE /details/1.json
  def destroy
    @detail.destroy
    respond_to do |format|
      format.html { redirect_to details_url, notice: 'Detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_params
      params.require(:detail).permit(:welcome, :about)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_footeredit.html.erb
<%= @details.last.welcome %>

app/views/details/_form.html.erb
<div class="featurewraper">
<%= form_for(@detail) do |f| %>
  <% if @detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
      <% @detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <h2>Welcome Message for home Page</h2>
    <%= f.text_area :welcome, :class => "niceinputbig" %>
  </div>
  
  <div class="field">
   <h2>Welcome Message for About Page</h2>
    <%= f.text_area :about, :class => "niceinputbig" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/details/edit.html.erb
<h2>Admin - Editing Detail</ha>

<%= render 'form' %>

<%= link_to 'Show', @detail %> |
<%= link_to 'Back', details_path %>

app/views/details/index.html.erb
<p id="notice"><%= notice %></p>


<div class="featurewraper">
  
  <h2>Administrator Control Page </h2><h2>Website Texte</h2>
  <h2><%= notice %></h2>
  <h2><%= link_to 'New Detail', new_detail_path %></h2>
<div class="footerdiv">
	 <h2>Welcome Message</h2>
  <p>  
  <% @details.each do |detail| %>
      
     <p>What to do!</p>
        <%= link_to 'Show', detail %>
        <%= link_to 'Edit', edit_detail_path(detail) %>
        <%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %>
      
    <% end %>
  
  </p>			
			
				
				
</div>
			
			
<div class="footerdiv">
 <h2>News Feed</h2>
  <p>  
  <% @details.each do |detail| %>
      
<p>Change it!</p>     
        <%= link_to 'Show', detail %>
        <%= link_to 'Edit', edit_detail_path(detail) %>
        <%= link_to 'Destroy', detail, method: :delete, data: { confirm: 'Are you sure?' } %>
      
    <% end %>
  
  </p>			
 
</div>
		
		
<div class="footerdiv">
    <h2>Spare Section</h2>
<p>This section can be used for a different message on the website for future use</p>

</div>


<div class="footerdiv">
  <h2>Latest order</h2>
		<p>The last order number was <%= @orders.last.id %>  </p>
		
		<p><%= @orders.last.title %>  </p>
		<p>The last order total was <%= number_to_currency(@orders.last.subtotal, :unit => '€') %> </p>
		
		
		</div>

</div>


<div class="featurewraper">
  
  <h2>Product Editing Section</h2>
  <h2><%= notice %></h2>
  <h2><%= link_to 'Add New Product', new_product_path %></h2>

<% @products.each do |product| %>
 <div class="footerdiv">
	<p><img class="adminimg" src="/assets/<%= product.image_name %>"  alt="an image"/> </p>
 <p>Name <%= product.title %></p>
 <p>
   
   Price <%= number_to_currency(product.price, :unit => '€') %></p>
 
 <p><%= link_to 'Edit', edit_product_path(product) %> </p>
<p><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  
</div>


    <% end %>
				
				

			
			

</div>




<div class="featurewraper">
  
  <h2>Order Viewing Section</h2>
  <h2><%= notice %></h2>

<% @orders.each do |order| %>
 <div class="footerdiv">
	 
	
  <p>Order Number: <%= order.id %></p>
  <p>Order Title: <%= order.title %></p>
  <p>Total Value: €<%= order.subtotal %></p>
  <p>User Ud: <%= order.user_id %></p>
 
  
 
 
  
</div>


    <% end %>
	
</div>


<div class="featurewraper">
  
  <h2>Order Items Viewing Section</h2>
  <h2><%= notice %></h2>


</div>

<div class="featurewraper">
  
  <h2>User Viewing Section</h2>
  <h2><%= notice %></h2>

<% @users.each do |user| %>
 <div class="footerdiv">
	 
  <p>User ID <%= user.id %></p>
  <p>First Name <%= user.name %></p>
  <p>Surname <%= user.surname %></p>
  <p>Unhappy? <%= button_to "Delete User", registration_path(resource_name), data: { confirm: "Are you sure?"}, method: :delete, :class => "formbutton" %></p>
 
  
  
</div>


    <% end %>
	
</div>

<div class="featurewraper">
  
  <h2>Order Viewing Section</h2>
  <h2><%= notice %></h2>

<% @users.each do |user| %>
 <div class="footerdiv">
	 
  <p>User ID <%= user.id %></p>
  <p>First Name <%= user.name %></p>
  <p>Surname <%= user.surname %></p>
  
 
  
  
</div>


    <% end %>
	
</div>

<div class="featurewraper">
  
  <h2>Order Item user ID</h2>
  <h2><%= notice %></h2>
<% @orderItem.each do |orderitem| %>
<div class="footerdiv">
<p> item number <%= orderitem.id %></p>
<p>Product ID <%= orderitem.product_id %></p>
<p>Order Number: <%= orderitem.order_id %></p>

  
  
 
 

 
</div>
 
   <% end %>
  
</div>

<div class="featurewraper">
  <h2>Admin Registration</h2>
  <h2>
	<% if admin_signed_in? %>
 
 		 	  Welcome <strong><%= current_admin.name %></strong>.
  			
  			<%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
  			<%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
				<% else %>
  			<%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
  		<%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
		
		<% end %>	
		</h2>
</div>  
	
</div>

app/views/details/new.html.erb
<h1>New Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>

app/views/details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Welcome:</strong>
  <%= @detail.welcome %>
</p>

<%= link_to 'Edit', edit_detail_path(@detail) %> |
<%= link_to 'Back', details_path %>